-- SQL to create tables in Supabase

-- Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL NOT NULL,
  image TEXT,
  category TEXT,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  city TEXT NOT NULL,
  area TEXT NOT NULL,
  address TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  transaction_id TEXT,
  total DECIMAL NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL,
  price DECIMAL NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Customers table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  password TEXT,
  address TEXT,
  city TEXT,
  area TEXT,
  profile_image TEXT,
  bio TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Admins table
CREATE TABLE admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  password TEXT,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security) - Optional, but recommended for production
-- For now, we'll keep it simple as the user might not have set up policies yet.
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- ... etc

-- Seed initial data
INSERT INTO products (name, description, price, image, category, stock) VALUES 
('Premium Drop Shoulder Tee', 'High-quality cotton drop shoulder t-shirt for a relaxed and stylish look.', 1250.00, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop', 'Drop Shoulder', 50),
('Royal Panjabi Collection', 'Exquisite Panjabi with intricate embroidery, perfect for special occasions.', 2500.00, 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop', 'Panjabi', 30),
('Not Today Tee', 'The official uniform for those days when your bed is your best friend. 100% organic cotton, 0% motivation.', 850.00, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop', 'Mood Swings', 50),
('Introverts Shield', 'A heavy-weight black tee that says I am here, but I am already thinking about leaving.', 1200.00, 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop', 'Introvert Vibes', 30),
('Sarcasm Loading...', 'A minimalist sage green tee for those who speak fluent sarcasm. Warning: May cause eye-rolls.', 950.00, 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop', 'Sarcasm Loaded', 40),
('Professional Procrastinator', 'A refined navy polo for someone who is very serious about doing things tomorrow.', 1500.00, 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=1000&auto=format&fit=crop', 'Work From Home', 25),
('Error 404: Social Skills', 'Soft heather grey tee for those moments when your social battery is at 0%.', 750.00, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop', 'Tech Humor', 15),
('Trust Me, I am a Designer', 'Earthy terracotta graphic tee. Perfect for pretending you know what you are doing.', 1100.00, 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop', 'Creative Chaos', 20);

INSERT INTO admins (email, password, role) VALUES ('admin@salamify.com', 'admin123', 'superadmin');
